import Link from "next/link";
import { ArrowRight, Check, Heart, BriefcaseBusiness, Users, BookOpen } from "lucide-react";
import { CHARACTER_TYPES, type CharacterType } from "@/data/types";
import type { DiagnosisResult } from "@/lib/diagnosis";
import { GOD_COPY } from "@/lib/diagnosis/ten-gods";
import { Character } from "./character";
import { ShareActions } from "./share-actions";
export function Profile({ type, result }: { type: CharacterType; result?: DiagnosisResult }) {
  const number = String(CHARACTER_TYPES.indexOf(type) + 1).padStart(2, "0");
  return <article className="profile page-width"><Link className="breadcrumb" href={result ? "/diagnose/" : "/types/"}>← {result ? "もう一度診断する" : "10タイプ図鑑へ"}</Link><div className="profile-hero"><div className="profile-art" style={{ background: type.color }}><span className="file-number">STELLA FILE / {number}</span><Character type={type} priority /><span className="art-label">{type.stem} · {type.motif}のエレメント</span></div><div className="profile-title"><p className="eyebrow">{result ? "YOUR PERSONALITY FILE" : "THE STELLA COLLECTION"}</p><p className="result-lead">{result ? "あなたのタイプは…" : `FILE ${number}`}</p><h1>{type.displayName}</h1><p className="profile-catch">{type.shortCatch}</p><div className="keywords">{type.keywords.map(word => <span key={word}>{word}</span>)}</div><ShareActions type={type} /></div></div>
    <div className="profile-body"><section><p className="eyebrow">THIS IS YOU</p><h2>あなたは、こんな人。</h2><p>{type.summary}</p></section><section className="strength-section"><p className="eyebrow">YOUR NATURAL GIFTS</p><h2>ちゃんとある、あなたの強み。</h2><ul className="strength-list">{type.strengths.map(item => <li key={item}><Check size={18} aria-hidden="true" />{item}</li>)}</ul>{result && <div className="god-insight"><span className="insight-label">もうひとつの強み / {result.tenGod}</span><h3>{GOD_COPY[result.tenGod].title}</h3><p>{GOD_COPY[result.tenGod].strength}</p><p className="gentle-tip">{GOD_COPY[result.tenGod].hint}</p><details><summary>この補足の読み解き方</summary><p className="micro">日干「{result.pillar.stem}」と、日支「{result.pillar.branch}」の蔵干・本気「{result.hiddenStem}」の関係から「{result.tenGod}」を算出しています。今回の補足は日支のみを使います。年柱・月柱・時柱を含む総合的な鑑定ではありません。</p><Link href="/about/">採用しているルールを見る</Link></details></div>}</section><div className="tendency-grid"><section><Heart size={23} strokeWidth={1.5} /><h2>恋愛のこと</h2><p>{type.romance}</p></section><section><BriefcaseBusiness size={23} strokeWidth={1.5} /><h2>仕事のこと</h2><p>{type.workStyle}</p></section><section><Users size={23} strokeWidth={1.5} /><h2>人間関係のこと</h2><p>{type.relationshipStyle}</p></section></div><section className="deeper-cta"><BookOpen size={25} strokeWidth={1.5} /><h2>もう少し、自分を知りたいあなたへ。</h2><p>この診断は、自分を知る小さな入り口。<br />読み方と、これから広げていく診断についてご紹介します。</p><Link className="text-link" href="/about/#next">診断をもっと楽しむ <ArrowRight size={17} /></Link></section><p className="micro disclaimer">性格や将来を断定するものではありません。しっくりくる言葉を、日々のヒントにしてみてください。</p><div className="profile-bottom"><Link className="button secondary" href="/types/">ほかの9タイプも見てみる <ArrowRight size={17} /></Link>{!result && <Link className="text-link" href="/diagnose/">自分のタイプを診断する →</Link>}</div></div></article>;
}
