import Link from "next/link";
import { ArrowRight, Check, Heart, BriefcaseBusiness, Users, BookOpen } from "lucide-react";
import { CHARACTER_TYPES, elementColors, type CharacterType } from "@/data/types";
import type { DiagnosisResult } from "@/lib/diagnosis";
import { GOD_COPY } from "@/lib/diagnosis/ten-gods";
import { Character } from "./character";
import { ShareActions } from "./share-actions";
export function Profile({ type, result }: { type: CharacterType; result?: DiagnosisResult }) {
  const number = String(CHARACTER_TYPES.indexOf(type) + 1).padStart(2, "0");
  const element = elementColors(type.stem);
  return <article className="profile page-width"><Link className="breadcrumb" href={result ? "/diagnose/" : "/types/"}>← {result ? "もう一度診断する" : "10タイプ図鑑へ"}</Link><div className="profile-hero"><div className="profile-art" style={{ background: element.tint, "--el": element.color } as React.CSSProperties}><span className="file-number">STELLA FILE / {number}</span><Character type={type} priority /><span className="art-label">モチーフ：{type.motif}</span></div><div className="profile-title"><p className="eyebrow">{result ? "YOUR PERSONALITY FILE" : "THE STELLA COLLECTION"}</p><p className="result-lead">{result ? "あなたのタイプは…" : `FILE ${number}`}</p><h1>{type.displayName}</h1><p className="profile-catch">{type.shortCatch}</p><div className="keywords">{type.keywords.map(word => <span key={word}>{word}</span>)}</div><ShareActions type={type} /></div></div>
    <div className="profile-body"><section><p className="eyebrow">THIS IS YOU</p><h2>あなたは、こんな人。</h2><p>{type.summary}</p></section><section className="strength-section"><p className="eyebrow">YOUR NATURAL GIFTS</p><h2>あなたの強み</h2><ul className="strength-list">{type.strengths.map(item => <li key={item}><Check size={18} aria-hidden="true" />{item}</li>)}</ul>{result && <div className="god-insight"><span className="insight-label">もうひとつの強み</span><h3>{GOD_COPY[result.tenGod].title}</h3><p>{GOD_COPY[result.tenGod].strength}</p><p className="gentle-tip">{GOD_COPY[result.tenGod].hint}</p></div>}</section><div className="tendency-grid"><section><Heart size={23} strokeWidth={1.5} /><h2>恋愛のこと</h2><p>{type.romance}</p></section><section><BriefcaseBusiness size={23} strokeWidth={1.5} /><h2>仕事のこと</h2><p>{type.workStyle}</p></section><section><Users size={23} strokeWidth={1.5} /><h2>人間関係のこと</h2><p>{type.relationshipStyle}</p></section></div><section className="deeper-cta"><BookOpen size={25} strokeWidth={1.5} /><h2>診断のしくみ</h2><p>タイプの決め方や、結果の見方をかんたんに説明しています。</p><Link className="text-link" href="/about/">診断について読む <ArrowRight size={17} /></Link></section><p className="micro disclaimer">性格や将来を決めつけるものではありません。当てはまるところだけ参考にしてください。</p><div className="profile-bottom"><Link className="button secondary" href="/types/">ほかの9タイプも見てみる <ArrowRight size={17} /></Link>{!result && <Link className="text-link" href="/diagnose/">自分のタイプを診断する →</Link>}</div></div></article>;
}
